use axum::Router;
use canonical_api_server::AppState;

pub(crate) mod handlers;
pub(crate) mod route;
// Generated by `ores-stack sync` and byte-compared by `ores-stack sync --check`.
// rustfmt would reflow it and make it stale, so it is left exactly as emitted.
#[rustfmt::skip]
pub(crate) mod rpc;

pub(crate) fn router() -> Router<AppState> {
    route::router()
}
