// @generated by ores-stack sync; do not edit
// Source authority: sibling handlers.rs. route.rs is only an optional HTTP projection.
// Regenerate with `ores-stack sync`; validate with `ores-stack sync --check`.

/// Consumer-supplied telemetry seam for guarded dispatch.
///
/// Same contract as the `RpcTelemetrySink` seam in `ORESoftware/api-docs`
/// (`runtime/rust/telemetry.rs`): the application owns the adapter and points
/// it at ores-otel / next-loggers. Nothing generated here links a telemetry
/// SDK, installs a provider, or decides sampling.
///
/// Arguments, in order: the operation key, the static `ores-routine-` id of
/// the dispatch, the static `ores-trace-` id of the call site, the outcome
/// (`"failed"` or `"panicked"`), and the receipt status when there is one.
///
/// Deliberately absent: request and response bodies, path and query values,
/// `meta` contents, headers, tokens, and every other payload value. A route
/// folder cannot know which fields are sensitive, so none of them cross this
/// boundary.
///
/// Fail-open: a sink that panics is caught at the emit and changes nothing
/// about the RPC result.
///
/// Optional by design: an application that does not name the adapter's type
/// never mentions this alias, and generated code must not fail a consumer's
/// `-D warnings` gate for a convenience it declined.
#[allow(dead_code)]
pub type RpcDispatchTelemetrySink<'a> = &'a dyn ::core::ops::Fn(
    &'static str,
    &'static str,
    &'static str,
    &'static str,
    ::core::option::Option<u16>,
);

macro_rules! dispatch {
    ($state:expr, $context:expr, $call:expr) => {{
        $crate::rpc_routes::version::rpc::dispatch!(
            $state,
            $context,
            $call,
            &|_key: &'static str,
              _routine_id: &'static str,
              _trace_id: &'static str,
              _outcome: &'static str,
              _status: ::core::option::Option<u16>| {}
        )
    }};
    ($state:expr, $context:expr, $call:expr, $telemetry:expr) => {{
        let __ores_call = $call;
        let __ores_sink = $telemetry;
        match __ores_call.key.as_str() {
            "canonical_cloud.version.get_version" => {
                const ORES_ROUTINE_ID: &str = "ores-routine-GBOHdK9aDEdqXCm1DETFq";
                let mut __ores_dispatch = ::std::boxed::Box::pin(
                    ::ores_api_docs::rpc_shared_operation::dispatch_typed_json_operation::<_, _, _, _>(
                        $state,
                        $context,
                        __ores_call,
                        $crate::rpc_routes::version::handlers::__ores_invoke_get_version,
                    ),
                );
                let __ores_guarded = ::std::future::poll_fn(|__ores_context| {
                    match ::std::panic::catch_unwind(::std::panic::AssertUnwindSafe(|| {
                        ::std::future::Future::poll(
                            ::std::pin::Pin::as_mut(&mut __ores_dispatch),
                            __ores_context,
                        )
                    })) {
                        ::std::result::Result::Ok(__ores_poll) => {
                            __ores_poll.map(::std::result::Result::Ok)
                        }
                        ::std::result::Result::Err(__ores_panic) => ::std::task::Poll::Ready(
                            ::std::result::Result::Err(__ores_panic),
                        ),
                    }
                })
                .await;
                match __ores_guarded {
                    ::std::result::Result::Ok(__ores_receipt) => {
                        if !__ores_receipt.ok {
                            // Log the failure, then return the receipt unchanged.
                            let _ = ::std::panic::catch_unwind(::std::panic::AssertUnwindSafe(|| {
                                __ores_sink(
                                    "canonical_cloud.version.get_version",
                                    ORES_ROUTINE_ID,
                                    "ores-trace-wsYrYB7Ls1ekT_0DY5yjq",
                                    "failed",
                                    __ores_receipt.status,
                                )
                            }));
                        }
                        __ores_receipt
                    }
                    ::std::result::Result::Err(__ores_panic) => {
                        // Log the panic, then resume it. A panic is never
                        // converted into a receipt or a silent error.
                        let _ = ::std::panic::catch_unwind(::std::panic::AssertUnwindSafe(|| {
                            __ores_sink(
                                "canonical_cloud.version.get_version",
                                ORES_ROUTINE_ID,
                                "ores-trace-V2Uh1MJ1ATlf-D-nZmPqp",
                                "panicked",
                                ::core::option::Option::None,
                            )
                        }));
                        ::std::panic::resume_unwind(__ores_panic)
                    }
                }
            }
            _ => unreachable!("RPC transport admitted an operation not owned by this route folder"),
        }
    }};
}

pub(crate) use dispatch;
