// @generated by `ores-stack rpc sync`; DO NOT EDIT.
// Source authority: sibling handlers.rs. route.rs is only an optional HTTP projection.
// Regenerate with `ores-stack sync`; validate with `ores-stack sync --check`.

macro_rules! dispatch {
    ($state:expr, $context:expr, $call:expr) => {{
        let __ores_call = $call;
        match __ores_call.key.as_str() {
            "canonical_cloud.version.get_version" => {
                ::ores_api_docs::rpc_shared_operation::dispatch_typed_json_operation::<
                    _,
                    $crate::rpc_routes::version::handlers::VersionOperation,
                    _,
                    _,
                >(
                    $state,
                    $context,
                    __ores_call,
                    $crate::rpc_routes::version::handlers::__ores_invoke_get_version,
                )
                .await
            }
            _ => unreachable!("generated route-local RPC dispatcher received an unknown key"),
        }
    }};
}

pub(crate) use dispatch;
