#!/usr/bin/env sh
set -eu
mode=${1:---full}; case "$mode" in --structural-only|--full) ;; *) exit 2;; esac
root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"; cd "$root"
fail(){ echo "[routing-conformance] $*" >&2; exit 1; }
for dir in contracts conformance src/routes; do [ -d "$dir" ] && [ ! -L "$dir" ] || fail "$dir must be a real non-symlink directory"; done
[ -z "$(find contracts conformance src/routes -type l -print -quit)" ] || fail 'symlinks are forbidden in routing authority/evidence trees'
for path in contracts/typespec/server-filesystem-routing.tsp contracts/json-schema/server-filesystem-routing.schema.json contracts/examples/server-filesystem-routing.json .zpkg.toml zed-env.toml .zed/pre-install .zed/post-install .githooks/pre-commit .githooks/pre-push scripts/install-git-hooks.sh; do [ -f "$path" ] && [ ! -L "$path" ] || fail "missing lifecycle authority: $path"; done
[ "$mode" = --full ] || exit 0
command -v zed >/dev/null 2>&1 || fail 'zed is required for full routing admission'
out="${TMPDIR:-/tmp}/canonical-api-routing-$$"; trap 'rm -rf "$out"' EXIT INT TERM; mkdir -p "$out"
zed run tjsv check --typespec="$root/contracts/typespec/server-filesystem-routing.tsp" --schema="$root/contracts/json-schema/server-filesystem-routing.schema.json" --report="$out/report.json" --output-dir="$out/generated" --quiet
zed run ores-stack check
found=0
find src/routes -type f -name handlers.rs -print | while IFS= read -r handlers; do
  dir=${handlers%/handlers.rs}; found=1
  for sibling in route.rs rpc.rs lambda.rs; do [ -f "$dir/$sibling" ] || fail "$dir missing required sibling $sibling"; done
  head -n 1 "$dir/rpc.rs" | grep -Fqx '// @generated by ores-stack sync; do not edit' || fail "$dir/rpc.rs has wrong generator marker"
  head -n 1 "$dir/lambda.rs" | grep -Fqx '// @generated by `ores-stack api lambda sync`; DO NOT EDIT.' || fail "$dir/lambda.rs has wrong generator marker"
done
python3 scripts/verify_interface_contract.py
cargo fmt --all -- --check
cargo test --all-targets --all-features --locked
cargo clippy --all-targets --all-features --locked -- -D warnings
