pub(crate) mod handlers;
pub(crate) mod http_projection;
// Generated by `ores-stack sync` and byte-compared by `ores-stack sync --check`.
// rustfmt would reflow it and make it stale, so it is left exactly as emitted.
#[rustfmt::skip]
pub(crate) mod rpc;
