// @generated by `ores-stack sync`; DO NOT EDIT.
// Source authority: sibling handlers.rs. route.rs is only an optional HTTP projection.

macro_rules! dispatch {
    ($state:expr, $context:expr, $call:expr) => {{
        let __ores_call = $call;
        match __ores_call.key.as_str() {
            "canonical_cloud.user.find_users" => {
                ::ores_api_docs::rpc_shared_operation::dispatch_typed_json_operation::<
                    _,
                    $crate::rpc_routes::user::handlers::FindUsersOperation,
                    _,
                    _,
                >(
                    $state,
                    $context,
                    __ores_call,
                    $crate::rpc_routes::user::handlers::__ores_invoke_find_users,
                )
                .await
            }
            "canonical_cloud.user.find_user_by_id" => {
                ::ores_api_docs::rpc_shared_operation::dispatch_typed_json_operation::<
                    _,
                    $crate::rpc_routes::user::handlers::FindUserByIdOperation,
                    _,
                    _,
                >(
                    $state,
                    $context,
                    __ores_call,
                    $crate::rpc_routes::user::handlers::__ores_invoke_find_user_by_id,
                )
                .await
            }
            _ => unreachable!("generated route-local RPC dispatcher received an unknown key"),
        }
    }};
}

pub(crate) use dispatch;
