// @generated by `ores-stack rpc sync`; DO NOT EDIT.
// Registry authority: src/**/handlers.rs operations not marked #[ores_no_rpc].
// Regenerate with `ores-stack sync`; validate with `ores-stack sync --check`.

use std::{future::Future, pin::Pin};

use axum::Router;
use canonical_api_server::AppState;
use ores_api_docs::{
    rpc_v1_router, RouteMap, RpcV1Call, RpcV1Dispatcher, RpcV1HttpContext, RpcV1Receipt,
};

use super::{user, version};

#[derive(Clone)]
struct Dispatcher {
    state: AppState,
}

impl RpcV1Dispatcher for Dispatcher {
    fn dispatch(
        &self,
        context: RpcV1HttpContext,
        call: RpcV1Call,
    ) -> Pin<Box<dyn Future<Output = RpcV1Receipt> + Send + 'static>> {
        let state = self.state.clone();
        Box::pin(async move {
            match call.key.as_str() {
                "canonical_cloud.version.get_version" => {
                    // `dispatch!` expands here, not in version::rpc. Bind the
                    // sibling handlers module at the expansion site so the
                    // generated macro stays module-layout agnostic.
                    use super::version::handlers;
                    version::rpc::dispatch!(state, context, call)
                }
                "canonical_cloud.user.find_users" | "canonical_cloud.user.find_user_by_id" => {
                    // Same macro-hygiene rule for the shared user authority.
                    use super::user::handlers;
                    user::rpc::dispatch!(state, context, call)
                }
                _ => unreachable!("rpc_v1_router rejects unknown operation keys before dispatch"),
            }
        })
    }
}

pub(super) fn router(state: AppState) -> Router {
    rpc_v1_router(route_map(), Dispatcher { state })
}

fn route_map() -> RouteMap {
    RouteMap::from_json_str(
        r#"{
          "schema_version":"1.0.0",
          "service":"canonical-api-server",
          "map":{
            "version_get":{
              "path":"/v1/version",
              "methods":["GET"],
              "rpc_key":"canonical_cloud.version.get_version",
              "authorization":{"mode":"public"},
              "transports":["http"]
            },
            "user_find_users":{
              "path":"/v1/find-users",
              "methods":["POST"],
              "rpc_key":"canonical_cloud.user.find_users",
              "authorization":{"mode":"authenticated"},
              "transports":["http"]
            },
            "user_find_by_id":{
              "path":"/v1/find-user-by-id",
              "methods":["POST"],
              "rpc_key":"canonical_cloud.user.find_user_by_id",
              "authorization":{"mode":"authenticated"},
              "transports":["http"]
            }
          }
        }"#,
    )
    .expect("generated Canonical regular RPC route map must be valid")
}
