// @generated by `ores-stack api lambda exports`; DO NOT EDIT.
//
// Bootstrap placeholder for the provider-neutral Lambda host boundary.
// `ores-stack generate lambda` replaces this generator-owned file with the
// handlers-derived dispatch exports before Lambda packaging. Keeping the
// ownership marker in the canonical template lets the template compile before
// generation while preserving strict authored-vs-generated ownership.
